Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelManagement.Security;
using HotelManagement.Controllers;
using HotelManagement.Models;
using HotelManagement.ViewModels;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace HotelManagement.Controllers
{
    [Route("[controller]/[action]")]
    public class RoomsController : Controller
    {
        private readonly IRoom _room;
        private readonly ILogger<RoomsController> _logger;
        
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IDataProtector protector;
        // GET: Rooms
        public RoomsController(ILogger<RoomsController> logger,
            IHostingEnvironment hostingEnvironment,
                              IDataProtectionProvider dataProtectionProvider,
                              DataProtectionPurposeStrings dataProtectionPurposeStrings,IRoom room)
        {
            this._room = room;
        }
        public ActionResult Index()
        {
            var model = this._room.GetAllRooms();

            return View(model);
        }

        // GET: Rooms/Details/5
        [Route("{id}")]
        public ViewResult Details(int id)
        {
           
           
            Rooms room = _room.GetRoom(id);
            if (room == null)
            {
                Response.StatusCode = 404;
                return View("RoomsNotFound", id);
            }

            RoomDetailsViewModel roomDetailsViewModel = new RoomDetailsViewModel()
            {
                room = room,
                roomDiscription = "Rooms Details"

            };
            return View(roomDetailsViewModel);

        }

        // GET: Rooms/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(RoomsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var room = _room.GetRoomByRoomNumber(model.RoomNumebr);
                if (room == null)
                {
                    Rooms newRoom = new Rooms
                    {

                        RoomNumebr = model.RoomNumebr,
                        types = model.types,
                        PhoneNumber = model.PhoneNumber,
                        Researved = model.IsResearved
                    };
                    _room.Add(newRoom);
                    return RedirectToAction("Details", new { id = newRoom.Id });
                }
                else
                {
                    ModelState.AddModelError("", "Room number can not be duplicate.");
                }

            }
            return View();
        }

        // GET: Rooms/Edit/5
        public ActionResult Edit(int id)
        {
            Rooms room = _room.GetRoom(id);
           
            if (room == null)
            {

                RoomsViewModel roomsEditViewModel = new RoomsViewModel
                {
                    Id = room.Id,
                    RoomNumebr = room.RoomNumebr,
                    PhoneNumber = room.PhoneNumber,
                    types = room.types,
                    IsResearved = room.Researved
                };
                return View(roomsEditViewModel);

            }
            return View();

        }

        // POST: Rooms/Edit/5
        [HttpPost]
        public IActionResult Edit(RoomsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Rooms room = _room.GetRoom(model.Id);
                var roomExist = _room.GetRoomByRoomNumber(model.RoomNumebr, model.Id);
                if (roomExist == null)
                {
                    room.Id = model.Id;
                    room.RoomNumebr = model.RoomNumebr;
                    room.types = model.types;
                    room.PhoneNumber = model.PhoneNumber;
                    room.Researved = model.IsResearved;

                    Rooms updateRooms = _room.Update(room);
                    return RedirectToAction("index");
                }

                else
                {
                    ModelState.AddModelError("", "Room number can not be duplicate.");
                }
            }
            
            return View();
        }

        // GET: Rooms/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Rooms/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/Error_NotNeeded.cshtml
 @model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

Views/Shared/NotFound.cshtml
 
@{
    ViewBag.Title = "Not Found";
}

<h1>ViewBag.ErrorMessage</h1>
<a asp-controller="home" asp-action="index">
    Click here to navigate home page.
</a>

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signinManager
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/js/Payment.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>

    </environment>
    <link href="~/css/site.css" rel="stylesheet" />
    <title>@ViewData["Title"]</title>

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand">
                <img src="~/images/Hotel/hotel.jpg" height="30" width="30" />
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsableNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsableNavbar">
                <ul class="navbar-nav">
                   
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="$" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-action="users" asp-controller="Home">
                                    Staff
                                </a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Clients">
                                    Clients
                                </a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Rooms">
                                    Rooms
                                </a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Reservations">
                                    Reservations
                                </a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Payments">
                                    Payment
                                </a>
                            </div>
                        </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    @if (signinManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <form method="post" asp-controller="Account" asp-action="logout">
                                <button type="submit" style="width:auto;color:black;" class="nav-link btn-link py-0">Logout @User.Identity.Name</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
                        </li>

                    }

                </ul>
            </div>
        </nav>
        <div>@RenderBody()</div>

        @if (IsSectionDefined("Scripts"))
        {
            @RenderSection("Scripts", required: false)
        }
    </div>
</body>
</html>